name: Y-Py

on:
  push:
    branches: [ main ]
    paths:
      - 'y-py/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'y-py/**'
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    defaults:
      run:
        working-directory: y-py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
            default: true
      - name: Build Package
        run: |
          pip install maturin
          maturin build --release --out dist
      - name: Install Dependencies
        run: |
          pip install pytest
          pip install y-py --no-index --find-links dist --force-reinstall
      - name: Run Tests
        run: pytest